services:
    node:
        container_name: nextjs.test
        ports:
            - "80:80"
        build:
            context: .
            dockerfile: docker/dockerfile
        volumes:
            - .:/var/www/html
        tty: true
        networks:
            development:
networks:
    development:
        external: true
