import type {Metadata} from "next";
import './globals.css';
import {ThemeProvider} from '@/app/providers/theme.provider';
import React from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ThemeProvider>
            <html lang="en">
            <body>
                {children}
            </body>
            </html>
        </ThemeProvider>
    );
}
